
# Generated by configure script
# date: Fri Apr 12 21:03:50 JST 2013
# pwd : /home/adam/projects/fbxkb
# args: 

BUILD := 
HOST := 
TARGET := 
PREFIX := /usr
EPREFIX := /usr
BINDIR := /usr/bin
SBINDIR := /usr/sbin
LIBEXECDIR := /usr/libexec
LIBDIR := /usr/lib
SYSCONFDIR := /usr/etc
DATADIR := /usr/share
INCLUDEDIR := /usr/include
MANDIR := /usr/man
INFODIR := /usr/info
LOCALSTATEDIR := /usr/var
TOPDIR := /home/adam/projects/fbxkb
VERSION := 1.0
XKB_LIST_FILE := /usr/share/X11/xkb/rules/base.lst
GLIB_CFLAGS := -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 
GLIB_LIBS := -lglib-2.0 
GLIB_VER := 2.34.3
GTK_CFLAGS := -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng15 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 
GTK_LIBS := -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
GTK_VER := 3.6.3
CFLAGSX := -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng15 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -fPIC 
LDFLAGSX := -lglib-2.0  -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  
