/*
# Generated by configure script
# date: Fri Apr 12 21:03:50 JST 2013
# pwd : /home/adam/projects/fbxkb
# args: 
*/
#define BUILD ""
#define HOST ""
#define TARGET ""
#define PREFIX "/usr"
#define EPREFIX "/usr"
#define BINDIR "/usr/bin"
#define SBINDIR "/usr/sbin"
#define LIBEXECDIR "/usr/libexec"
#define LIBDIR "/usr/lib"
#define SYSCONFDIR "/usr/etc"
#define DATADIR "/usr/share"
#define INCLUDEDIR "/usr/include"
#define MANDIR "/usr/man"
#define INFODIR "/usr/info"
#define LOCALSTATEDIR "/usr/var"
#define TOPDIR "/home/adam/projects/fbxkb"
#define VERSION "1.0"
#define XKB_LIST_FILE "/usr/share/X11/xkb/rules/base.lst"
#define GLIB_CFLAGS "-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include "
#define GLIB_LIBS "-lglib-2.0 "
#define GLIB_VER "2.34.3"
#define GTK_CFLAGS "-pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng15 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include "
#define GTK_LIBS "-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 "
#define GTK_VER "3.6.3"
#define CFLAGSX "-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng15 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -fPIC "
#define LDFLAGSX "-lglib-2.0  -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  "
