include /home/adam/projects/fbxkb/config.mk

install : local_install

local_install :
	install -m 755 -d $(DESTDIR)$(DATADIR)/fbxkb/images
	install -m 644 *.png $(DESTDIR)$(DATADIR)/fbxkb/images

include /home/adam/projects/fbxkb/rules.mk
